# Generated by Django 5.1.3 on 2024-11-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_file_post_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='document',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d', verbose_name='Post file'),
        ),
    ]
