# Generated by Django 5.1.3 on 2024-11-28 21:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='guest_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
