# Generated by Django 5.1.3 on 2024-12-03 21:41

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_guest_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='guest_token_expiration',
            field=models.DateTimeField(default=posts.models.get_default_guest_token_expiration),
        ),
    ]
