# Generated by Django 5.1.3 on 2024-12-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_guest_token_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Guest Name'),
        ),
    ]
