# Generated by Django 5.1.4 on 2024-12-31 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_title_alter_project_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='additional_users',
            field=models.ManyToManyField(blank=True, related_name='accessible_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
